<?php
declare(strict_types=1);
/**
 * Многоуровневое меню «Услуги» для выезжающей панели шапки.
 * У категории можно задать ключ href; иначе в меню используется /services.
 * Пункт подменю — строка или ['label' => '…', 'href' => '…'] (href по умолчанию /services).
 */
$siteHeaderMenuServices = [
    [
        'title' => 'Аудиторские услуги',
        'href' => '/audit',
        'items' => [
            ['label' => 'Обязательный аудит', 'href' => '/audit/obyazatelnyj-audit'],
            ['label' => 'Инициативный аудит', 'href' => '/audit/iniciativnyj-audit'],
            ['label' => 'Комплексный аудит', 'href' => '/audit/kompleksnyj-audit'],
            ['label' => 'Налоговый аудит', 'href' => '/audit/nalogovyj-audit'],
            ['label' => 'Аудит финансовой отчётности', 'href' => '/audit/audit-finansovoj-otchetnosti'],
            ['label' => 'Кадровый аудит', 'href' => '/kadrovyy-audit'],
        ],
    ],
    [
        'title' => 'Налоговый консалтинг и налоговая безопасность',
        'href' => '/konsalting',
        'items' => [
            ['label' => 'Налоговое консультирование', 'href' => '/konsalting/nalogovoe-konsultirovanie'],
            ['label' => 'Налоговый аудит / диагностика', 'href' => '/konsalting/nalogovaya-diagnostika'],
            ['label' => 'Услуги оптимизации налогов', 'href' => '/konsalting/optimizatsiya-nalogov'],
            ['label' => 'Возражения на акт налоговой', 'href' => '/konsalting/vozrazheniya-na-akt'],
            ['label' => 'Ответ на требование налогового органа', 'href' => '/konsalting/otvet-na-trebovanie-nalogovoj'],
            ['label' => 'Оптимизация видов налогов', 'href' => '/konsalting/optimizatsiya-vidov-nalogov'],
            ['label' => 'Оптимизация для юрлиц', 'href' => '/konsalting/optimizatsiya-dlya-yurlic'],
            ['label' => 'Консультации по налогам', 'href' => '/konsalting/konsultatsii-po-nalogam'],
            ['label' => 'Пакет должной осмотрительности', 'href' => '/konsalting/paket-dolzhnoj-osmotritelnosti'],
            ['label' => 'Пакет безопасности сделок', 'href' => '/konsalting/paket-bezopasnosti-sdelok'],
            ['label' => 'Сопровождение похода в налоговую инспекцию', 'href' => '/konsalting/soprovozhdenie-nalogovoj-inspektsii'],
        ],
    ],
    [
        'title' => 'Финансовый консалтинг и оценка',
        'href' => '/finans',
        'items' => [
            ['label' => 'Финансовый анализ компании', 'href' => '/finans/finansovyy-analiz-kompanii'],
            ['label' => 'Финансовое моделирование', 'href' => '/finans/finansovoe-modelirovanie'],
            ['label' => 'Оценка бизнеса', 'href' => '/finans/otsenka-biznesa'],
            ['label' => 'Оценка активов (имущество, НМА)', 'href' => '/finans/otsenka-aktivov'],
            ['label' => 'Инвестиционный анализ', 'href' => '/finans/investitsionnyy-analiz'],
            ['label' => 'Анализ финансово-хозяйственной деятельности предприятия', 'href' => '/finans/analiz-fhdy-predpriyatiya'],
            ['label' => 'Постановка и сопровождение финансового учета в компании', 'href' => '/finans/postanovka-finansovogo-ucheta'],
            ['label' => 'Предоставление финансовых отчётов для судов', 'href' => '/finans/finansovye-otchety-dlya-sudov'],
            ['label' => 'Финансовый анализ компании для пользователей', 'href' => '/finans/finansovyy-analiz-dlya-polzovateley'],
            ['label' => 'Разработка финансовой модели', 'href' => '/finans/razrabotka-finansovoy-modeli'],
            ['label' => 'Автоматизация финансового учета', 'href' => '/finans/avtomatizatsiya-finansovogo-ucheta'],
            ['label' => 'Аудит инвестиционного портфеля', 'href' => '/finans/audit-investitsionnogo-portfelya'],
            ['label' => 'Предоставление консультаций по размещению активов', 'href' => '/finans/konsultatsii-po-razmeshcheniyu-aktivov'],
        ],
    ],
    [
        'title' => 'Бухгалтерский консалтинг и аутсорсинг',
        'href' => '/buhgalteriya',
        'items' => [
            ['label' => 'Бухгалтерское сопровождение', 'href' => '/buhgalteriya/buhgalterskoe-soprovozhdenie'],
            ['label' => 'Восстановление бухгалтерского учета', 'href' => '/buhgalteriya/vosstanovlenie-buhucheta'],
            ['label' => 'Аутсорсинг кадрового учета', 'href' => '/buhgalteriya/autsorsing-kadrovogo-ucheta'],
            ['label' => 'Бухгалтерия Безлимитная', 'href' => '/buhgalteriya/buhgalteriya-bezlimitnaya'],
            ['label' => 'Аутсорсинг на время декрета Главбуха', 'href' => '/buhgalteriya/autsorsing-dekret-glavbuh'],
            ['label' => 'Аутсорсинг иностранной компании', 'href' => '/buhgalteriya/autsorsing-inostrannoy-kompanii'],
            ['label' => 'Бухгалтерское сопровождение ВЭД', 'href' => '/buhgalteriya/buhgalteriya-ved'],
            ['label' => 'Аутсорсинг по отраслям', 'href' => '/buhgalteriya/autsorsing-po-otraslyam'],
            ['label' => 'Аутсорсинг заработной платы', 'href' => '/buhgalteriya/autsorsing-zarplaty'],
            ['label' => 'Сопровождение главного бухгалтера', 'href' => '/buhgalteriya/soprovozhdenie-glavbuh'],
        ],
    ],
    [
        'title' => 'Форензик',
        'href' => '/forenzik',
        'items' => [
            ['label' => 'Расследование финансовых мошенничеств', 'href' => '/forenzik/rassledovanie-finansovyh-moshennichestv'],
            ['label' => 'Проверка контрагентов', 'href' => '/forenzik/proverka-kontragentov'],
            ['label' => 'Антикоррупционные расследования', 'href' => '/forenzik/antikorrupcionnye-rassledovaniya'],
            ['label' => 'Анализ подозрительных операций', 'href' => '/forenzik/analiz-podozritelnyh-operatsiy'],
            ['label' => 'Корпоративные расследования', 'href' => '/forenzik/korporativnye-rassledovaniya'],
            ['label' => 'Сбор доказательств для суда', 'href' => '/forenzik/sbor-dokazatelstv-dlya-suda'],
            ['label' => 'Эффективная система безопасности', 'href' => '/forenzik/effektivnaya-sistema-bezopasnosti'],
            ['label' => 'Анализ утечек и злоупотреблений', 'href' => '/forenzik/analiz-utechek-i-zloupotrebleniy'],
            ['label' => 'Проверка сотрудников (fraud check)', 'href' => '/forenzik/proverka-sotrudnikov-fraud-check'],
            ['label' => 'Digital forensic (цифровые расследования)', 'href' => '/forenzik/digital-forensic'],
            ['label' => 'Форензик при сделках (M&A)', 'href' => '/forenzik/forenzik-pri-sdelkah-ma'],
        ],
    ],
    [
        'title' => 'Кадровый аудит',
        'href' => '/kadrovyy-audit',
        'items' => [
            ['label' => 'Аудит кадрового делопроизводства', 'href' => '/kadrovyy-audit/audit-kadrovogo-deloproizvodstva'],
            ['label' => 'Проверка трудовых договоров', 'href' => '/kadrovyy-audit/proverka-trudovyh-dogovorov'],
            ['label' => 'Аудит начисления зарплаты', 'href' => '/kadrovyy-audit/audit-nachisleniya-zarplaty'],
            ['label' => 'Проверка соблюдения ТК', 'href' => '/kadrovyy-audit/proverka-soblyudeniya-tk'],
            ['label' => 'Кадровые риски и штрафы', 'href' => '/kadrovyy-audit/kadrovye-riski-i-shtrafy'],
            ['label' => 'Восстановление кадрового учета', 'href' => '/kadrovyy-audit/vosstanovlenie-kadrovogo-ucheta'],
            ['label' => 'Постановка HR-процессов', 'href' => '/kadrovyy-audit/postanovka-hr-protsessov'],
            ['label' => 'Разработка кадровой политики', 'href' => '/kadrovyy-audit/razrabotka-kadrovoy-politiki'],
            ['label' => 'Аудит HR-документооборота', 'href' => '/kadrovyy-audit/audit-hr-dokumentooborota'],
            ['label' => 'Подготовка к проверкам ГИТ', 'href' => '/kadrovyy-audit/podgotovka-k-proverkam-git'],
        ],
    ],
    [
        'title' => 'МСФО и международная отчетность',
        'href' => '/msfo',
        'items' => [
            ['label' => 'Подготовка отчетности по МСФО', 'href' => '/msfo/podgotovka-otchetnosti-po-msfo'],
            ['label' => 'Переход на МСФО', 'href' => '/msfo/perehod-na-msfo'],
            ['label' => 'Первое применение МСФО', 'href' => '/msfo/pervoe-primenenie-msfo'],
            ['label' => 'Аудит отчетности по МСФО', 'href' => '/msfo/audit-otchetnosti-po-msfo'],
            ['label' => 'Автоматизация учета по МСФО', 'href' => '/msfo/avtomatizatsiya-ucheta-po-msfo'],
            ['label' => 'Обзорная проверка по МСФО', 'href' => '/msfo/obzornaya-proverka-po-msfo'],
            ['label' => 'Помощь в подготовке МСФО', 'href' => '/msfo/pomoshch-v-podgotovke-msfo'],
            ['label' => 'Обучение теории и практике МСФО', 'href' => '/msfo/obuchenie-teorii-i-praktike-msfo'],
            ['label' => 'Разработка учетной политики МСФО', 'href' => '/msfo/razrabotka-uchetnoj-politiki-msfo'],
            ['label' => 'Заполнение консолидационных пакетов МСФО', 'href' => '/msfo/zapolnenie-konsolidatsionnyh-paketov-msfo'],
        ],
    ],
    [
        'title' => 'Комплаенс, риск-контроль, внутренний аудит',
        'href' => '/komplaens',
        'items' => [
            ['label' => 'Внутренний аудит', 'href' => '/komplaens/vnutrenniy-audit'],
            ['label' => 'Построение системы внутреннего контроля (СВК)', 'href' => '/komplaens/postroenie-sistemy-vnutrennego-kontrolya-svk'],
            ['label' => 'Комплаенс-система', 'href' => '/komplaens/komplaens-sistema'],
            ['label' => 'Управление рисками (risk management)', 'href' => '/komplaens/upravlenie-riskami'],
            ['label' => 'Антикоррупционный комплаенс', 'href' => '/komplaens/antikorrupcionnyy-komplaens'],
            ['label' => 'AML / противодействие отмыванию', 'href' => '/komplaens/aml-protivodeystvie-otmyvaniyu'],
            ['label' => 'Оценка рисков бизнеса', 'href' => '/komplaens/ocenka-riskov-biznesa'],
        ],
    ],
    [
        'title' => 'Консалтинг и сопровождение бизнеса',
        'href' => '/biznes-konsalting',
        'items' => [
            ['label' => 'Стратегический консалтинг', 'href' => '/biznes-konsalting/strategicheskiy-konsalting'],
            ['label' => 'Управленческий консалтинг', 'href' => '/biznes-konsalting/upravlencheskiy-konsalting'],
            ['label' => 'Бизнес-планирование', 'href' => '/biznes-konsalting/biznes-planirovanie'],
            ['label' => 'Сопровождение сделок (M&A)', 'href' => '/biznes-konsalting/soprovozhdenie-sdelok-ma'],
            ['label' => 'Регистрация бизнеса', 'href' => '/biznes-konsalting/registratsiya-biznesa'],
            ['label' => 'Ликвидация и реорганизация', 'href' => '/biznes-konsalting/likvidatsiya-i-reorganizatsiya'],
            ['label' => 'Услуги по инвентаризации имущества', 'href' => '/biznes-konsalting/uslugi-po-inventarizatsii-imuschestva'],
            ['label' => 'Бухгалтерские консультации', 'href' => '/biznes-konsalting/buhgalterskie-konsultatsii'],
            ['label' => 'Консультации по налогам', 'href' => '/biznes-konsalting/konsultatsii-po-nalogam'],
            ['label' => 'Юридические консалтинговые услуги', 'href' => '/biznes-konsalting/yuridicheskie-konsaltingovye-uslugi'],
            ['label' => 'Управленческий учет', 'href' => '/biznes-konsalting/upravlencheskiy-uchet'],
            ['label' => 'Автоматизация управленческого учета', 'href' => '/biznes-konsalting/avtomatizatsiya-upravlencheskogo-ucheta'],
            ['label' => 'Услуги по регистрации ООО', 'href' => '/biznes-konsalting/uslugi-po-registratsii-ooo'],
            ['label' => 'Подготовка ЛНА', 'href' => '/biznes-konsalting/podgotovka-lna'],
        ],
    ],
    [
        'title' => 'Обучение и академия HSEP',
        'href' => '/hsep',
        'items' => [
            ['label' => 'Курсы для бухгалтеров', 'href' => '/hsep/kursy-dlya-buhgalterov'],
            ['label' => 'Курсы по налогам', 'href' => '/hsep/kursy-po-nalogam'],
            ['label' => 'Обучение МСФО', 'href' => '/hsep/obuchenie-msfo'],
            ['label' => 'Обучение внутреннему аудиту', 'href' => '/hsep/obuchenie-vnutrennemu-auditu'],
            ['label' => 'Повышение квалификации аудиторов', 'href' => '/hsep/povyshenie-kvalifikatsii-auditorov'],
            ['label' => 'Корпоративное обучение', 'href' => '/hsep/korporativnoe-obuchenie'],
            ['label' => 'Онлайн-курсы', 'href' => '/hsep/onlayn-kursy'],
            ['label' => 'Семинары и вебинары', 'href' => '/hsep/seminary-i-vebinary'],
            ['label' => 'Сертификационные программы', 'href' => '/hsep/sertifikatsionnye-programmy'],
        ],
    ],
    [
        'title' => 'DUE diligence',
        'href' => '/due-diligence',
        'items' => [
            ['label' => 'Финансовый Due Diligence', 'href' => '/due-diligence/finansovyy-due-diligence'],
            ['label' => 'Налоговый', 'href' => '/due-diligence/nalogovyy-due-diligence'],
            ['label' => 'Юридический', 'href' => '/due-diligence/yuridicheskiy-due-diligence'],
            ['label' => 'Операционный', 'href' => '/due-diligence/operatsionnyy-due-diligence'],
            ['label' => 'Комплексный', 'href' => '/due-diligence/kompleksnyy-due-diligence'],
            ['label' => 'Due Diligence для инвесторов', 'href' => '/due-diligence/due-diligence-dlya-investorov'],
        ],
    ],
];
